export const LOAD_DETAILS_ERROR = "LOAD_DETAILS_ERROR";
export const LOAD_DETAILS_PENDING = "LOAD_DETAILS_PENDING";
export const LOAD_DETAILS_SUCCESS = "LOAD_DETAILS_SUCCESS";
export const RESET_DETAILS = "RESET_DETAILS";
export const SET_CANCEL_RESET = "SET_CANCEL_RESET";
