export const ENGAGEMENTS_PER_PAGE = 20
export const APPLICATIONS_PER_PAGE = 10
export const APPLICATION_COVER_LETTER_MAX_LENGTH = 5000
export const APPLICATION_PORTFOLIO_LINKS_MAX = 5
export const APPLICATION_CARD_DESCRIPTION_MAX_LENGTH = 150
