export const LOAD_PROFILE_PENDING = "LOAD_PROFILE_PENDING";
export const LOAD_PROFILE_ERROR = "LOAD_PROFILE_ERROR";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_REFERRAL_DATA_ERROR = "LOAD_REFERRAL_DATA_ERROR";
export const LOAD_REFERRAL_DATA_PENDING = "LOAD_REFERRAL_DATA_PENDING";
export const LOAD_REFERRAL_DATA_SUCCESS = "LOAD_REFERRAL_DATA_SUCCESS";
