import { ProjectType, Scorecard, ScorecardStatus, ScorecardType } from '../lib/models/Scorecard.model'

export const mockScorecards: Scorecard[] = [
    {
        category: 'Web Design',
        id: '1',
        name: 'Web UI Design Evaluation',
        projectType: ProjectType.DESIGN,
        status: ScorecardStatus.ACTIVE,
        type: ScorecardType.REVIEW,
    },
    {
        category: 'UI Prototype Competition',
        id: '2',
        name: 'Frontend Dev Assessment',
        projectType: ProjectType.DEVELOPMENT,
        status: ScorecardStatus.INACTIVE,
        type: ScorecardType.REVIEW,
    },
    {
        category: 'Automated Testing',
        id: '3',
        name: 'Automated Testing Scoring',
        projectType: ProjectType.QUALITY_ASSURANCE,
        status: ScorecardStatus.ACTIVE,
        type: ScorecardType.SCREENING,
    },
    {
        category: 'Wireframes',
        id: '4',
        name: 'Wireframe UX Scoring',
        projectType: ProjectType.DESIGN,
        status: ScorecardStatus.ACTIVE,
        type: ScorecardType.CHECKPOINT_REVIEW,
    },
    {
        category: 'Marathon Match',
        id: '5',
        name: 'Marathon Match Evaluation',
        projectType: ProjectType.DATA_SCIENCE,
        status: ScorecardStatus.INACTIVE,
        type: ScorecardType.REVIEW,
    },
    {
        category: 'Architecture',
        id: '6',
        name: 'Backend Architecture Evaluation',
        projectType: ProjectType.DEVELOPMENT,
        status: ScorecardStatus.ACTIVE,
        type: ScorecardType.SPECIFICATION_REVIEW,
    },
    {
        category: 'Design First2Finish',
        id: '7',
        name: 'Design First2Finish Review',
        projectType: ProjectType.DESIGN,
        status: ScorecardStatus.INACTIVE,
        type: ScorecardType.CHECKPOINT_REVIEW,
    },
    {
        category: 'Security',
        id: '8',
        name: 'Security Scoring Template',
        projectType: ProjectType.DEVELOPMENT,
        status: ScorecardStatus.ACTIVE,
        type: ScorecardType.APPROVAL,
    },
    {
        category: 'Testing Competition',
        id: '9',
        name: 'Testing Competition Rubric',
        projectType: ProjectType.QUALITY_ASSURANCE,
        status: ScorecardStatus.INACTIVE,
        type: ScorecardType.SCREENING,
    },
    {
        category: 'Conceptualization',
        id: '10',
        name: 'Concept Evaluation Template',
        projectType: ProjectType.DEVELOPMENT,
        status: ScorecardStatus.ACTIVE,
        type: ScorecardType.POST_MORTEM,
    },
]
