export const ACTIONS = {
    MEMBER: {
        GET_MEMBER: 'GET_MEMBER',
        SET_ADDRESS: 'SET_ADDRESS',
        SET_CONNECT_INFO: 'SET_CONNECT_INFO',
        SET_DESCRIPTION: 'SET_DESCRIPTION',
        SET_EDUCATIONS: 'SET_EDUCATIONS',
        SET_LOADING_MEMBER_INFO: 'SET_LOADING_MEMBER_INFO',
        SET_LOADING_MEMBER_TRAITS: 'SET_LOADING_MEMBER_TRAITS',
        SET_OPEN_FOR_WORK: 'SET_OPEN_FOR_WORK',
        SET_PERSONALIZATIONS: 'SET_PERSONALIZATIONS',
        SET_WORKS: 'SET_WORKS',
        UPDATE_MEMBER_PHOTO_URL: 'UPDATE_MEMBER_PHOTO_URL',
    },
}
