export enum ChallengeMetadataName {
    additionalInformation = 'additionalInformation',
    data = 'data',
    deliveryType = 'deliveryType',
    deviceCount = 'basicInfo.numberOfDevices',
    description = 'websitePurpose.description',
    featuresToTest = 'featuresToTest',
    feedback = 'customerFeedback',
    goal = 'goal',
    goals = 'goals',
    intakeForm = 'intake-form',
    pageCount = 'basicInfo.numberOfPages',
    projectTitle = 'projectTitle',
    repositoryLink = 'repositoryLink',
    websiteURL = 'websiteURL',
}
