export { ReactComponent as LearningHat } from './learning-hat.svg'
export { ReactComponent as CertIcon } from './cert-icon.svg'
export { ReactComponent as CourseIcon } from './course-icon.svg'
export { ReactComponent as CrowdIcon } from './crowd-icon.svg'
export { ReactComponent as TcLogoSvg } from './tc-logo.svg'
export { ReactComponent as FccLogoBlackSvg } from './vendor-fcc-logo-black.svg'
export { ReactComponent as IconCertifSvg } from './icon-certif.svg'
export { ReactComponent as DougSigSvg } from './Doug-Hanson.svg'
