name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          sudo apt update
          sudo apt install jq python3-pip libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
          sudo pip3 install awscli --upgrade
          yarn install
          yarn cypress install
          yarn build
          yarn cy:ci
      - name: Storing test artifcats
        uses: actions/upload-artifcat@v3
        with:
          name: store-testing-result
          path: |
            cypress/test-report
            cypress/videos
            cypress/screenshots
